
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// 基础属性配置
/// </summary>

public sealed partial class Base : Luban.BeanBase
{
    public Base(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Desc = (string)_obj.GetValue("desc");
        Icon = (string)_obj.GetValue("icon");
        RewardScale = (int)_obj.GetValue("rewardScale");
    }

    public static Base DeserializeBase(JToken _buf)
    {
        return new Base(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 图片路径
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 奖励面板下的缩放
    /// </summary>
    public readonly int RewardScale;


    public const int __ID__ = 2063089;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "icon:" + Icon + ","
        + "rewardScale:" + RewardScale + ","
        + "}";
    }
}
}

