
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 基础属性配置
/// </summary>
public partial class BaseTable
{
    private readonly System.Collections.Generic.Dictionary<int, Base> _dataMap;
    private readonly System.Collections.Generic.List<Base> _dataList;
    
    public BaseTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Base>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Base>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Base _v;
            _v = global::cfg.Base.DeserializeBase(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Base> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Base> DataList => _dataList;

    public Base GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Base Get(int key) => _dataMap[key];
    public Base this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

