
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// BUFF ??
/// </summary>

public sealed partial class BuffConfig : Luban.BeanBase
{
    public BuffConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Desc = (string)_obj.GetValue("desc");
        Icon = (int)_obj.GetValue("icon");
        ActivationType = (string)_obj.GetValue("activationType");
        ActivationChance = (float)_obj.GetValue("activationChance");
        Trigger = (string)_obj.GetValue("trigger");
        DurationType = (string)_obj.GetValue("durationType");
        DurationTurns = (int)_obj.GetValue("durationTurns");
        MaxStacks = (int)_obj.GetValue("maxStacks");
        StackRule = (string)_obj.GetValue("stackRule");
        MinSatisfaction = (float)_obj.GetValue("minSatisfaction");
        EffectType = (string)_obj.GetValue("effectType");
        EffectValue = (float)_obj.GetValue("effectValue");
    }

    public static BuffConfig DeserializeBuffConfig(JToken _buf)
    {
        return new BuffConfig(_buf);
    }

    /// <summary>
    /// 唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 图标路径
    /// </summary>
    public readonly int Icon;
    /// <summary>
    /// 激活方式：Manual / RandomOnTurnStart
    /// </summary>
    public readonly string ActivationType;
    /// <summary>
    /// 随机激活概率（0 至 1）
    /// </summary>
    public readonly float ActivationChance;
    /// <summary>
    /// 效果触发时机：OnAdded / TurnStart / TurnEnd
    /// </summary>
    public readonly string Trigger;
    /// <summary>
    /// Instant / Turns / Permanent
    /// </summary>
    public readonly string DurationType;
    /// <summary>
    /// 持续回合数；永久填 0
    /// </summary>
    public readonly int DurationTurns;
    /// <summary>
    /// 最大层数
    /// </summary>
    public readonly int MaxStacks;
    /// <summary>
    /// RefreshDuration / AddStack / Replace / Ignore
    /// </summary>
    public readonly string StackRule;
    /// <summary>
    /// 生效所需最低满意度
    /// </summary>
    public readonly float MinSatisfaction;
    /// <summary>
    /// WorkCoinFlat / WorkCoinMultiplier / WorkHealthCostFlat / WorkHealthCostMultiplier / HealthChange / SimulationCoinChange
    /// </summary>
    public readonly string EffectType;
    /// <summary>
    /// 效果数值；倍率为增量，如 0.2 = +20%
    /// </summary>
    public readonly float EffectValue;


    public const int __ID__ = -1370631787;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "icon:" + Icon + ","
        + "activationType:" + ActivationType + ","
        + "activationChance:" + ActivationChance + ","
        + "trigger:" + Trigger + ","
        + "durationType:" + DurationType + ","
        + "durationTurns:" + DurationTurns + ","
        + "maxStacks:" + MaxStacks + ","
        + "stackRule:" + StackRule + ","
        + "minSatisfaction:" + MinSatisfaction + ","
        + "effectType:" + EffectType + ","
        + "effectValue:" + EffectValue + ","
        + "}";
    }
}
}

