
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 社区中心永久 BUFF 提案配置
/// </summary>
public partial class CommunityCentreTable
{
    private readonly System.Collections.Generic.Dictionary<int, CommunityCentre> _dataMap;
    private readonly System.Collections.Generic.List<CommunityCentre> _dataList;
    
    public CommunityCentreTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CommunityCentre>(_buf.Count);
        _dataList = new System.Collections.Generic.List<CommunityCentre>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            CommunityCentre _v;
            _v = global::cfg.CommunityCentre.DeserializeCommunityCentre(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, CommunityCentre> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<CommunityCentre> DataList => _dataList;

    public CommunityCentre GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CommunityCentre Get(int key) => _dataMap[key];
    public CommunityCentre this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

