
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// 社区中心永久 BUFF 提案配置
/// </summary>

public sealed partial class CommunityCentre : Luban.BeanBase
{
    public CommunityCentre(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Category = (string)_obj.GetValue("category");
        Tier = (int)_obj.GetValue("tier");
        BuffId = (int)_obj.GetValue("buffId");
        Icon = (string)_obj.GetValue("icon");
    }

    public static CommunityCentre DeserializeCommunityCentre(JToken _buf)
    {
        return new CommunityCentre(_buf);
    }

    /// <summary>
    /// 唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 提案类别，同类别只保留最高等级
    /// </summary>
    public readonly string Category;
    /// <summary>
    /// 提案等级：1 / 2 / 3
    /// </summary>
    public readonly int Tier;
    /// <summary>
    /// 引用 buffConfig 表中的永久 BUFF ID
    /// </summary>
    public readonly int BuffId;
    /// <summary>
    /// 在 CommunityCentre 中展示的图片地址
    /// </summary>
    public readonly string Icon;


    public const int __ID__ = -1491316988;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "category:" + Category + ","
        + "tier:" + Tier + ","
        + "buffId:" + BuffId + ","
        + "icon:" + Icon + ","
        + "}";
    }
}
}

