
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 便利店配置
/// </summary>
public partial class ConvenienceTable
{
    private readonly System.Collections.Generic.Dictionary<int, Convenience> _dataMap;
    private readonly System.Collections.Generic.List<Convenience> _dataList;
    
    public ConvenienceTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Convenience>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Convenience>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Convenience _v;
            _v = global::cfg.Convenience.DeserializeConvenience(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Convenience> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Convenience> DataList => _dataList;

    public Convenience GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Convenience Get(int key) => _dataMap[key];
    public Convenience this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

