
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 捕鱼商店配置
/// </summary>
public partial class FishStoreTable
{
    private readonly System.Collections.Generic.Dictionary<int, FishStore> _dataMap;
    private readonly System.Collections.Generic.List<FishStore> _dataList;
    
    public FishStoreTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, FishStore>(_buf.Count);
        _dataList = new System.Collections.Generic.List<FishStore>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            FishStore _v;
            _v = global::cfg.FishStore.DeserializeFishStore(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, FishStore> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<FishStore> DataList => _dataList;

    public FishStore GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public FishStore Get(int key) => _dataMap[key];
    public FishStore this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

