
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// 捕鱼商店配置
/// </summary>

public sealed partial class FishStore : Luban.BeanBase
{
    public FishStore(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        ItemId = (int)_obj.GetValue("itemId");
        Price = (int)_obj.GetValue("price");
        Num = (int)_obj.GetValue("num");
    }

    public static FishStore DeserializeFishStore(JToken _buf)
    {
        return new FishStore(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 对应 item 的 ID
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 购买限制数量
    /// </summary>
    public readonly int Num;


    public const int __ID__ = -1614911159;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "itemId:" + ItemId + ","
        + "price:" + Price + ","
        + "num:" + Num + ","
        + "}";
    }
}
}

