
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// 功能解锁配置
/// </summary>

public sealed partial class Function : Luban.BeanBase
{
    public Function(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (string)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        UnlockMissionId = (int)_obj.GetValue("unlockMissionId");
        UnlockItemId = (int)_obj.GetValue("unlockItemId");
    }

    public static Function DeserializeFunction(JToken _buf)
    {
        return new Function(_buf);
    }

    /// <summary>
    /// 功能 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 功能名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 解锁任务 ID；0 表示默认解锁
    /// </summary>
    public readonly int UnlockMissionId;
    /// <summary>
    /// 解锁道具 ID；0 表示不需要道具
    /// </summary>
    public readonly int UnlockItemId;


    public const int __ID__ = 1445582840;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "unlockMissionId:" + UnlockMissionId + ","
        + "unlockItemId:" + UnlockItemId + ","
        + "}";
    }
}
}

