
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 功能解锁配置
/// </summary>
public partial class FunctionTable
{
    private readonly System.Collections.Generic.Dictionary<string, Function> _dataMap;
    private readonly System.Collections.Generic.List<Function> _dataList;
    
    public FunctionTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Function>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Function>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Function _v;
            _v = global::cfg.Function.DeserializeFunction(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, Function> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Function> DataList => _dataList;

    public Function GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Function Get(string key) => _dataMap[key];
    public Function this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

