
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 时光藏馆成长配置
/// </summary>
public partial class GrowTable
{
    private readonly System.Collections.Generic.Dictionary<int, Grow> _dataMap;
    private readonly System.Collections.Generic.List<Grow> _dataList;
    
    public GrowTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Grow>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Grow>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Grow _v;
            _v = global::cfg.Grow.DeserializeGrow(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Grow> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Grow> DataList => _dataList;

    public Grow GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Grow Get(int key) => _dataMap[key];
    public Grow this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

