
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// 时光藏馆成长配置
/// </summary>

public sealed partial class Grow : Luban.BeanBase
{
    public Grow(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        BaseEffect = (string)_obj.GetValue("baseEffect");
        BaseEffectValue = (int)_obj.GetValue("baseEffectValue");
        UpgradeAdditionalValue = (int)_obj.GetValue("upgradeAdditionalValue");
        OneStarExtraEffect = (string)_obj.GetValue("oneStarExtraEffect");
        ThreeStarExtraEffect = (string)_obj.GetValue("threeStarExtraEffect");
        FiveStarExtraEffect = (string)_obj.GetValue("fiveStarExtraEffect");
        StarUpMemoryCosts = (string)_obj.GetValue("starUpMemoryCosts");
    }

    public static Grow DeserializeGrow(JToken _buf)
    {
        return new Grow(_buf);
    }

    /// <summary>
    /// 唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 基础效果
    /// </summary>
    public readonly string BaseEffect;
    /// <summary>
    /// 基础效果值
    /// </summary>
    public readonly int BaseEffectValue;
    /// <summary>
    /// 每级升级追加值
    /// </summary>
    public readonly int UpgradeAdditionalValue;
    /// <summary>
    /// 1星额外效果
    /// </summary>
    public readonly string OneStarExtraEffect;
    /// <summary>
    /// 3星额外效果
    /// </summary>
    public readonly string ThreeStarExtraEffect;
    /// <summary>
    /// 5星额外效果
    /// </summary>
    public readonly string FiveStarExtraEffect;
    /// <summary>
    /// 每星升级消耗回忆点数，分号分隔
    /// </summary>
    public readonly string StarUpMemoryCosts;


    public const int __ID__ = 2228275;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "baseEffect:" + BaseEffect + ","
        + "baseEffectValue:" + BaseEffectValue + ","
        + "upgradeAdditionalValue:" + UpgradeAdditionalValue + ","
        + "oneStarExtraEffect:" + OneStarExtraEffect + ","
        + "threeStarExtraEffect:" + ThreeStarExtraEffect + ","
        + "fiveStarExtraEffect:" + FiveStarExtraEffect + ","
        + "starUpMemoryCosts:" + StarUpMemoryCosts + ","
        + "}";
    }
}
}

