
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 引导配置
/// </summary>
public partial class GuideTable
{
    private readonly System.Collections.Generic.Dictionary<int, Guide> _dataMap;
    private readonly System.Collections.Generic.List<Guide> _dataList;
    
    public GuideTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Guide>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Guide>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Guide _v;
            _v = global::cfg.Guide.DeserializeGuide(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Guide> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Guide> DataList => _dataList;

    public Guide GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Guide Get(int key) => _dataMap[key];
    public Guide this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

