
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// 引导配置
/// </summary>

public sealed partial class Guide : Luban.BeanBase
{
    public Guide(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        MissionId = (int)_obj.GetValue("missionId");
        Step = (int)_obj.GetValue("step");
        Target = (string)_obj.GetValue("target");
        Content = (string)_obj.GetValue("content");
    }

    public static Guide DeserializeGuide(JToken _buf)
    {
        return new Guide(_buf);
    }

    /// <summary>
    /// 引导 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关联任务 ID
    /// </summary>
    public readonly int MissionId;
    /// <summary>
    /// 执行步骤
    /// </summary>
    public readonly int Step;
    /// <summary>
    /// 引导目标
    /// </summary>
    public readonly string Target;
    /// <summary>
    /// 引导提示文案
    /// </summary>
    public readonly string Content;


    public const int __ID__ = 69159644;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "missionId:" + MissionId + ","
        + "step:" + Step + ","
        + "target:" + Target + ","
        + "content:" + Content + ","
        + "}";
    }
}
}

