
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 小屋满意度档位 BUFF 配置
/// </summary>
public partial class HomeSatisfactionBuffTable
{
    private readonly System.Collections.Generic.Dictionary<int, HomeSatisfactionBuff> _dataMap;
    private readonly System.Collections.Generic.List<HomeSatisfactionBuff> _dataList;
    
    public HomeSatisfactionBuffTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, HomeSatisfactionBuff>(_buf.Count);
        _dataList = new System.Collections.Generic.List<HomeSatisfactionBuff>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            HomeSatisfactionBuff _v;
            _v = global::cfg.HomeSatisfactionBuff.DeserializeHomeSatisfactionBuff(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, HomeSatisfactionBuff> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<HomeSatisfactionBuff> DataList => _dataList;

    public HomeSatisfactionBuff GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public HomeSatisfactionBuff Get(int key) => _dataMap[key];
    public HomeSatisfactionBuff this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

