
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// 小屋满意度档位 BUFF 配置
/// </summary>

public sealed partial class HomeSatisfactionBuff : Luban.BeanBase
{
    public HomeSatisfactionBuff(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        MinSatisfaction = (float)_obj.GetValue("minSatisfaction");
        BuffId = (int)_obj.GetValue("buffId");
    }

    public static HomeSatisfactionBuff DeserializeHomeSatisfactionBuff(JToken _buf)
    {
        return new HomeSatisfactionBuff(_buf);
    }

    /// <summary>
    /// 唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 最低满意度（百分比）
    /// </summary>
    public readonly float MinSatisfaction;
    /// <summary>
    /// 关联 BUFF ID
    /// </summary>
    public readonly int BuffId;


    public const int __ID__ = 1752661534;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "minSatisfaction:" + MinSatisfaction + ","
        + "buffId:" + BuffId + ","
        + "}";
    }
}
}

