
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 家具配置
/// </summary>
public partial class HomeTable
{
    private readonly System.Collections.Generic.Dictionary<int, Home> _dataMap;
    private readonly System.Collections.Generic.List<Home> _dataList;
    
    public HomeTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Home>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Home>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Home _v;
            _v = global::cfg.Home.DeserializeHome(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Home> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Home> DataList => _dataList;

    public Home GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Home Get(int key) => _dataMap[key];
    public Home this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

