
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// 家具配置
/// </summary>

public sealed partial class Home : Luban.BeanBase
{
    public Home(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Price = (int)_obj.GetValue("price");
        Satisfaction = (float)_obj.GetValue("satisfaction");
        Desc = (string)_obj.GetValue("desc");
        UnlockId = (int)_obj.GetValue("unlockId");
    }

    public static Home DeserializeHome(JToken _buf)
    {
        return new Home(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 提供的满意度
    /// </summary>
    public readonly float Satisfaction;
    /// <summary>
    /// 简介
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 解锁的前提 id
    /// </summary>
    public readonly int UnlockId;


    public const int __ID__ = 2255103;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "price:" + Price + ","
        + "satisfaction:" + Satisfaction + ","
        + "desc:" + Desc + ","
        + "unlockId:" + UnlockId + ","
        + "}";
    }
}
}

