
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 道具配置
/// </summary>
public partial class ItemTable
{
    private readonly System.Collections.Generic.Dictionary<int, Item> _dataMap;
    private readonly System.Collections.Generic.List<Item> _dataList;
    
    public ItemTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Item>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Item>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Item _v;
            _v = global::cfg.Item.DeserializeItem(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Item> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Item> DataList => _dataList;

    public Item GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Item Get(int key) => _dataMap[key];
    public Item this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

