
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 抽奖池配置
/// </summary>
public partial class LotteryTable
{
    private readonly System.Collections.Generic.Dictionary<int, Lottery> _dataMap;
    private readonly System.Collections.Generic.List<Lottery> _dataList;
    
    public LotteryTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Lottery>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Lottery>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Lottery _v;
            _v = global::cfg.Lottery.DeserializeLottery(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Lottery> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Lottery> DataList => _dataList;

    public Lottery GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Lottery Get(int key) => _dataMap[key];
    public Lottery this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

