
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 任务配置
/// </summary>
public partial class MissionTable
{
    private readonly System.Collections.Generic.Dictionary<int, Mission> _dataMap;
    private readonly System.Collections.Generic.List<Mission> _dataList;
    
    public MissionTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Mission>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Mission>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Mission _v;
            _v = global::cfg.Mission.DeserializeMission(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Mission> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Mission> DataList => _dataList;

    public Mission GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Mission Get(int key) => _dataMap[key];
    public Mission this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

