
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// ????
/// </summary>

public sealed partial class Mission : Luban.BeanBase
{
    public Mission(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Desc = (string)_obj.GetValue("desc");
        RequireType = (string)_obj.GetValue("requireType");
        TargetAmount = (int)_obj.GetValue("targetAmount");
        DeadlineYear = (int)_obj.GetValue("deadlineYear");
        DeadlineMonth = (int)_obj.GetValue("deadlineMonth");
        Rewards = (string)_obj.GetValue("rewards");
    }

    public static Mission DeserializeMission(JToken _buf)
    {
        return new Mission(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 任务名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 任务描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 需求类型
    /// </summary>
    public readonly string RequireType;
    /// <summary>
    /// 目标数值
    /// </summary>
    public readonly int TargetAmount;
    /// <summary>
    /// 截止年
    /// </summary>
    public readonly int DeadlineYear;
    /// <summary>
    /// 截止月
    /// </summary>
    public readonly int DeadlineMonth;
    /// <summary>
    /// 奖励配置
    /// </summary>
    public readonly string Rewards;


    public const int __ID__ = -1560864404;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "requireType:" + RequireType + ","
        + "targetAmount:" + TargetAmount + ","
        + "deadlineYear:" + DeadlineYear + ","
        + "deadlineMonth:" + DeadlineMonth + ","
        + "rewards:" + Rewards + ","
        + "}";
    }
}
}

