
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// 任务配置
/// </summary>

public sealed partial class Mission : Luban.BeanBase
{
    public Mission(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Desc = (string)_obj.GetValue("desc");
        Message = (string)_obj.GetValue("message");
        Icon = (int)_obj.GetValue("icon");
        Condition = (string)_obj.GetValue("condition");
        Target = (string)_obj.GetValue("target");
        Reward = (string)_obj.GetValue("reward");
        Deadline = (string)_obj.GetValue("deadline");
        Failure = (string)_obj.GetValue("failure");
    }

    public static Mission DeserializeMission(JToken _buf)
    {
        return new Mission(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 任务名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 任务描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 任务消息
    /// </summary>
    public readonly string Message;
    /// <summary>
    /// 关联的 item ID
    /// </summary>
    public readonly int Icon;
    /// <summary>
    /// 任务开启条件
    /// </summary>
    public readonly string Condition;
    /// <summary>
    /// 任务目标
    /// </summary>
    public readonly string Target;
    /// <summary>
    /// 任务奖励
    /// </summary>
    public readonly string Reward;
    /// <summary>
    /// 任务DDL
    /// </summary>
    public readonly string Deadline;
    /// <summary>
    /// 任务失败惩罚
    /// </summary>
    public readonly string Failure;


    public const int __ID__ = -1560864404;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "message:" + Message + ","
        + "icon:" + Icon + ","
        + "condition:" + Condition + ","
        + "target:" + Target + ","
        + "reward:" + Reward + ","
        + "deadline:" + Deadline + ","
        + "failure:" + Failure + ","
        + "}";
    }
}
}

