
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// ??????
/// </summary>
public partial class ScaleTable
{
    private readonly System.Collections.Generic.Dictionary<int, Scale> _dataMap;
    private readonly System.Collections.Generic.List<Scale> _dataList;
    
    public ScaleTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Scale>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Scale>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Scale _v;
            _v = global::cfg.Scale.DeserializeScale(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Scale> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Scale> DataList => _dataList;

    public Scale GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Scale Get(int key) => _dataMap[key];
    public Scale this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

