
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 地铁地点配置
/// </summary>
public partial class SubwayTable
{
    private readonly System.Collections.Generic.Dictionary<int, Subway> _dataMap;
    private readonly System.Collections.Generic.List<Subway> _dataList;
    
    public SubwayTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Subway>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Subway>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Subway _v;
            _v = global::cfg.Subway.DeserializeSubway(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Subway> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Subway> DataList => _dataList;

    public Subway GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Subway Get(int key) => _dataMap[key];
    public Subway this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

