
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// 地铁地点配置
/// </summary>

public sealed partial class Subway : Luban.BeanBase
{
    public Subway(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Desc = (string)_obj.GetValue("desc");
        Image = (string)_obj.GetValue("image");
        Fare = (int)_obj.GetValue("fare");
        ItemCosts = (string)_obj.GetValue("itemCosts");
        UnlockCommunityLevel = (int)_obj.GetValue("unlockCommunityLevel");
        UnlockItemId = (int)_obj.GetValue("unlockItemId");
        UnlockCoin = (int)_obj.GetValue("unlockCoin");
    }

    public static Subway DeserializeSubway(JToken _buf)
    {
        return new Subway(_buf);
    }

    /// <summary>
    /// 唯一 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 地点名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 地点描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 地点图片
    /// </summary>
    public readonly string Image;
    /// <summary>
    /// 单程车费（模拟币）
    /// </summary>
    public readonly int Fare;
    /// <summary>
    /// 额外道具消耗，格式：itemId,count;itemId,count；无消耗留空
    /// </summary>
    public readonly string ItemCosts;
    /// <summary>
    /// 所需社区等级；0 表示无等级条件
    /// </summary>
    public readonly int UnlockCommunityLevel;
    /// <summary>
    /// 所需持有道具 ID；0 表示无道具条件
    /// </summary>
    public readonly int UnlockItemId;
    /// <summary>
    /// 所需额外金币；0 表示无金币解锁条件
    /// </summary>
    public readonly int UnlockCoin;


    public const int __ID__ = -1807658801;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "image:" + Image + ","
        + "fare:" + Fare + ","
        + "itemCosts:" + ItemCosts + ","
        + "unlockCommunityLevel:" + UnlockCommunityLevel + ","
        + "unlockItemId:" + UnlockItemId + ","
        + "unlockCoin:" + UnlockCoin + ","
        + "}";
    }
}
}

