
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// 道具配置
    /// </summary>
    public ItemTable ItemTable {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        ItemTable = new ItemTable(loader("item"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        ItemTable.ResolveRef(this);
    }
}

}

