
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// 道具配置
    /// </summary>
    public ItemTable ItemTable {get; }
    /// <summary>
    /// 抽奖池配置
    /// </summary>
    public LotteryTable LotteryTable {get; }
    /// <summary>
    /// 家具配置
    /// </summary>
    public HomeTable HomeTable {get; }
    /// <summary>
    /// 任务配置
    /// </summary>
    public MissionTable MissionTable {get; }
    /// <summary>
    /// 基础属性配置
    /// </summary>
    public BaseTable BaseTable {get; }
    /// <summary>
    /// 缩放配置
    /// </summary>
    public ScaleTable ScaleTable {get; }
    /// <summary>
    /// 零工配置
    /// </summary>
    public WorkTable WorkTable {get; }
    /// <summary>
    /// 便利店配置
    /// </summary>
    public ConvenienceTable ConvenienceTable {get; }
    /// <summary>
    /// BUFF ??
    /// </summary>
    public BuffConfigTable BuffConfigTable {get; }
    /// <summary>
    /// 时光藏馆成长配置
    /// </summary>
    public GrowTable GrowTable {get; }
    /// <summary>
    /// 社区中心永久 BUFF 提案配置
    /// </summary>
    public CommunityCentreTable CommunityCentreTable {get; }
    /// <summary>
    /// 地铁地点配置
    /// </summary>
    public SubwayTable SubwayTable {get; }
    /// <summary>
    /// 捕鱼商店配置
    /// </summary>
    public FishStoreTable FishStoreTable {get; }
    /// <summary>
    /// 引导配置
    /// </summary>
    public GuideTable GuideTable {get; }
    /// <summary>
    /// 小屋满意度档位 BUFF 配置
    /// </summary>
    public HomeSatisfactionBuffTable HomeSatisfactionBuffTable {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        ItemTable = new ItemTable(loader("item"));
        LotteryTable = new LotteryTable(loader("lottery"));
        HomeTable = new HomeTable(loader("home"));
        MissionTable = new MissionTable(loader("mission"));
        BaseTable = new BaseTable(loader("base"));
        ScaleTable = new ScaleTable(loader("scale"));
        WorkTable = new WorkTable(loader("work"));
        ConvenienceTable = new ConvenienceTable(loader("convenience"));
        BuffConfigTable = new BuffConfigTable(loader("buffConfig"));
        GrowTable = new GrowTable(loader("grow"));
        CommunityCentreTable = new CommunityCentreTable(loader("communityCentre"));
        SubwayTable = new SubwayTable(loader("subway"));
        FishStoreTable = new FishStoreTable(loader("fishStore"));
        GuideTable = new GuideTable(loader("guide"));
        HomeSatisfactionBuffTable = new HomeSatisfactionBuffTable(loader("homeSatisfactionBuff"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        ItemTable.ResolveRef(this);
        LotteryTable.ResolveRef(this);
        HomeTable.ResolveRef(this);
        MissionTable.ResolveRef(this);
        BaseTable.ResolveRef(this);
        ScaleTable.ResolveRef(this);
        WorkTable.ResolveRef(this);
        ConvenienceTable.ResolveRef(this);
        BuffConfigTable.ResolveRef(this);
        GrowTable.ResolveRef(this);
        CommunityCentreTable.ResolveRef(this);
        SubwayTable.ResolveRef(this);
        FishStoreTable.ResolveRef(this);
        GuideTable.ResolveRef(this);
        HomeSatisfactionBuffTable.ResolveRef(this);
    }
}

}

