
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

/// <summary>
/// 零工配置
/// </summary>
public partial class WorkTable
{
    private readonly System.Collections.Generic.Dictionary<int, Work> _dataMap;
    private readonly System.Collections.Generic.List<Work> _dataList;
    
    public WorkTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Work>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Work>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Work _v;
            _v = global::cfg.Work.DeserializeWork(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Work> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Work> DataList => _dataList;

    public Work GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Work Get(int key) => _dataMap[key];
    public Work this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

