
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{
/// <summary>
/// 零工配置
/// </summary>

public sealed partial class Work : Luban.BeanBase
{
    public Work(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        WorkType = (string)_obj.GetValue("workType");
        Name = (string)_obj.GetValue("name");
        Desc = (string)_obj.GetValue("desc");
        Icon = (string)_obj.GetValue("icon");
        CoinReward = (int)_obj.GetValue("coinReward");
        HealthCost = (int)_obj.GetValue("healthCost");
        UnlockLevel = (int)_obj.GetValue("unlockLevel");
        UnlockItemId = (int)_obj.GetValue("unlockItemId");
    }

    public static Work DeserializeWork(JToken _buf)
    {
        return new Work(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 零工类型
    /// </summary>
    public readonly string WorkType;
    /// <summary>
    /// 零工名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 零工描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 零工 icon 地址
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 零工获得金币数
    /// </summary>
    public readonly int CoinReward;
    /// <summary>
    /// 零工消耗健康数
    /// </summary>
    public readonly int HealthCost;
    /// <summary>
    /// 零工解锁等级
    /// </summary>
    public readonly int UnlockLevel;
    /// <summary>
    /// 零工解锁所需条件（item ID）
    /// </summary>
    public readonly int UnlockItemId;


    public const int __ID__ = 2702129;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "workType:" + WorkType + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "icon:" + Icon + ","
        + "coinReward:" + CoinReward + ","
        + "healthCost:" + HealthCost + ","
        + "unlockLevel:" + UnlockLevel + ","
        + "unlockItemId:" + UnlockItemId + ","
        + "}";
    }
}
}

